---
title: Hit the Schnitzel!
permalink: pretty
text_font: Noto Sans
heading_font: Roboto Condensed
description: Pound the fluidness out of Schnitzels!!!
plugins:
- jekyll-sass-converter
sass:
  style: compressed
url: https://schnitzel.wtf
baseurl:
game_bgd: /images/bgd.jpg