---
title: Hit the Schnitzel!
permalink: pretty
text_font: Noto Sans
heading_font: Roboto Condensed
description: Pound the fluidness out of Schnitzels!!!
plugins:
- jekyll-sass-converter
sass:
  style: compressed
url: https://schnitzel.wtf
baseurl:
game_bgd: https://www.chip.de/ii/6/8/9/7/7/3/7/8/6bad68e093e17899.jpeg
welcome_bgd: https://www.chip.de/ii/6/8/9/7/7/3/7/8/6bad68e093e17899.jpeg